name: SBOM and Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t chakravartikothadiya/sample-ngnix-server:v1 .

      - name: Log into Docker Hub (or other container registry)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.0.5

      - name: Generate Cosign keys
        run: |
          mkdir -p ~/.cosign
          openssl genpkey -algorithm ED25519 -out ~/.cosign/private.key
          openssl pkey -in ~/.cosign/private.key -pubout -out ~/.cosign/public.key

      - name: Assign private key to secret
        run: |
          echo "::add-mask::$(cat ~/.cosign/private.key)"
          echo "::add-mask::$(cat ~/.cosign/public.key)"
          echo "::set-env name=COSIGN_PRIVATE_KEY::$(cat ~/.cosign/private.key)"
          echo "::set-env name=COSIGN_PUBLIC_KEY::$(cat ~/.cosign/public.key)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Push Docker image to registry
        run: docker push chakravartikothadiya/sample-ngnix-server:v1
