name: SBOM and Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t chakravartikothadiya/sample-ngnix-server .

      - name: Log into Docker Hub (or other container registry)
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to registry
        run: docker push chakravartikothadiya/sample-ngnix-server
